### ISSUE TITLE
Create a Demo Preview site

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/timber-lite#29]
It could be useful for users to have a full demo preview of how Timber Lite could look like, even we're not able to make it available for import (yet) due to WPorg restrictions. 

Let's duplicate the main demo and install the lite version on it on: http://demos.pixelgrade.com/timber-lite

**Comment by georgeolaru** [comment]
The duplicate version of Timber (pro) is live here: https://demos.pixelgrade.com/timber-lite/

@madalingorbanescu Can you please install the Lite version and remove the content that it's only available in the Pro version?

**Comment by madalingorbanescu** [comment]
Done.
