### ISSUE TITLE
Wordpress 5.3 "$ is not a function"

### ISSUE THREAD

**Issue by Raaff** [pixelgrade/timber-lite#34]
Timber-lite is completely blank after the update to Wordpress 5.3.
Using $( instead of jQuery( is not working anymore. More info: https://core.trac.wordpress.org/ticket/48568
Fix: replace "$(" with "jQuery(" in assets/js/main.min.js

**Comment by madalingorbanescu** [comment]
Hey Raaff, thank you for reporting this. The issue is fixed now and an update will be released soon.
